name: Output information
on: workflow_dispatch
jobs:
    output_info:
        name: output_info
        runs-on: ubuntu-latest
        steps:
            - name: Output Github context
              run: echo "${{ toJson(github) }}"
